/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/performances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 공연 목록 조회
         * @description 모든 공연 목록을 조회합니다.
         */
        get: operations["PerformanceApiController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/performances/main/ranked": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 순위별 공연 목록 조회
         * @description 모든 장르에서 순위(rnum)가 있는 공연만 순위순으로 반환합니다.
         */
        get: operations["PerformanceApiController_findRankedPerformances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/performances/main/by-genre": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 장르별 공연 목록 조회
         * @description 지정한 장르의 모든 공연을 순위순으로 반환합니다.
         */
        get: operations["PerformanceApiController_findPerformancesByGenre"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/performances/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 공연 상세 정보 조회
         * @description 공연 ID를 파라미터로 받아 공연의 상세 정보를 반환합니다.
         */
        get: operations["PerformanceApiController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PerformanceSummaryDto: {
            /**
             * @description 공연 ID
             * @example PF277653
             */
            mt20id: string;
            /**
             * @description 공연명
             * @example 정선아리랑 토요상설공연: 뗏꾼
             */
            prfnm: string;
            /**
             * @description 공연 시작일
             * @example 2025.04.05
             */
            prfpdfrom: string;
            /**
             * @description 공연 종료일
             * @example 2025.11.22
             */
            prfpdto: string;
            /**
             * @description 공연 출연진
             * @example 홍동주, 최진실, 이재욱
             */
            prfcast: Record<string, never> | null;
            /**
             * @description 포스터 이미지 URL
             * @example http://www.kopis.or.kr/upload/pfmPoster/PF_PF277653_251029_130842.png
             */
            poster: string;
        };
        PerformanceDetailDto: {
            /**
             * @description 공연 ID
             * @example PF277653
             */
            mt20id: string;
            /**
             * @description 공연명
             * @example 정선아리랑 토요상설공연: 뗏꾼
             */
            prfnm: string;
            /**
             * @description 공연 시작일
             * @example 2025.04.05
             */
            prfpdfrom: string;
            /**
             * @description 공연 종료일
             * @example 2025.11.22
             */
            prfpdto: string;
            /**
             * @description 공연 출연진
             * @example 홍동주, 최진실, 이재욱
             */
            prfcast: Record<string, never> | null;
            /**
             * @description 포스터 이미지 URL
             * @example http://www.kopis.or.kr/upload/pfmPoster/PF_PF277653_251029_130842.png
             */
            poster: string;
            /**
             * @description 공연장르
             * @example 대중음악
             */
            genrenm: string;
            /**
             * @description 공연장소
             * @example 정선아리랑센터
             */
            fcltynm: Record<string, never> | null;
            /**
             * @description 공연상태
             * @example 공연중
             */
            prfstate: Record<string, never> | null;
            /**
             * @description 공연 런타임
             * @example 150분
             */
            prfruntime: Record<string, never> | null;
            /**
             * @description 관람연령
             * @example 8세 이상
             */
            prfage: Record<string, never> | null;
            /**
             * @description 가격
             * @example VIP석 150,000원, R석 100,000원
             */
            pcseguidance: Record<string, never> | null;
            /**
             * @description 상영시간대
             * @example 화~일 19:30, 토 15:00
             */
            dtguidance: Record<string, never> | null;
            /**
             * @description 공연 제작진
             * @example 연출: 홍길동, 작곡: 김철수
             */
            prfcrew: Record<string, never> | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    PerformanceApiController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 공연 목록 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 공연 목록을 성공적으로 조회했습니다. */
                        message?: string;
                        data?: components["schemas"]["PerformanceSummaryDto"][];
                    };
                };
            };
        };
    };
    PerformanceApiController_findRankedPerformances: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 순위별 공연 목록 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 순위별 공연 목록을 성공적으로 조회했습니다. */
                        message?: string;
                        data?: components["schemas"]["PerformanceSummaryDto"][];
                    };
                };
            };
        };
    };
    PerformanceApiController_findPerformancesByGenre: {
        parameters: {
            query: {
                /** @description 장르명 (필수) */
                genre: "복합" | "연극" | "뮤지컬" | "대중무용" | "대중음악" | "서양음악(클래식)" | "한국음악(국악)" | "서커스/마술" | "무용(서양/한국무용)";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 장르별 공연 목록 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 장르별 공연 목록을 성공적으로 조회했습니다. */
                        message?: string;
                        data?: components["schemas"]["PerformanceSummaryDto"][];
                    };
                };
            };
            /** @description genre 파라미터가 없을 경우 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 400 */
                        statusCode?: number;
                        /** @example genre 파라미터는 필수입니다. */
                        message?: string;
                        /** @example Bad Request */
                        error?: string;
                    };
                };
            };
        };
    };
    PerformanceApiController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 공연 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 공연 상세 정보 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 공연 상세 정보를 성공적으로 조회했습니다. */
                        message?: string;
                        data?: components["schemas"]["PerformanceDetailDto"];
                    };
                };
            };
            /** @description 공연을 찾을 수 없을 경우 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 404 */
                        statusCode?: number;
                        /** @example 공연 ID PF277653를 찾을 수 없습니다. */
                        message?: string;
                        /** @example Not Found */
                        error?: string;
                    };
                };
            };
        };
    };
}
